Update master.yml

diff --git a/.github/workflows/master.yml b/.github/workflows/master.yml
--- a/.github/workflows/master.yml
+++ b/.github/workflows/master.yml
@@ -29,16 +29,9 @@ jobs:
         python -m pip install --upgrade pip
         pip install flake8 pytest
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
-#     - name: Lint with flake8
-#       run: |
-#         # stop the build if there are Python syntax errors or undefined names
-#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       env:
         MPLBACKEND: TkAgg
-      uses: GabrielBB/xvfb-action@v1.2
       run: |
         pytest --ignore=W605
 
@@ -66,43 +59,43 @@ jobs:
       uses: codecov/codecov-action@v1
       with:
         file: ./coverage.xml
-  sphinx:
-    # If the above worked:
-    # Build docs and upload to GH Pages
-    needs: unittest
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up Python 3.7
-      uses: actions/setup-python@v1
-      with:
-        python-version: 3.7
-    - name: Install dependencies
-      run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
-        pip install .
-    - name: Build docs
-      run: |
-        cd docs
-        make html
-        # Tell GitHub not to use jekyll to compile the docs
-        touch build/html/.nojekyll
-        cd ../
-    - name: Commit documentation changes
-      run: |
-        git clone https://github.com/petercorke/spatialmath-python.git --branch gh-pages --single-branch gh-pages
-        cp -r docs/build/html/* gh-pages/
-        cd gh-pages
-        git config --local user.email "action@github.com"
-        git config --local user.name "GitHub Action"
-        git add .
-        git commit -m "Update documentation" -a || true
-        # The above command will fail if no changes were present, so we ignore
-        # that.
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        branch: gh-pages
-        directory: gh-pages
-        github_token: ${{ secrets.GITHUB_TOKEN }}
+#   sphinx:
+#     # If the above worked:
+#     # Build docs and upload to GH Pages
+#     needs: unittest
+#     runs-on: ubuntu-latest
+#     steps:
+#     - uses: actions/checkout@v2
+#     - name: Set up Python 3.7
+#       uses: actions/setup-python@v1
+#       with:
+#         python-version: 3.7
+#     - name: Install dependencies
+#       run: |
+#         python -m pip install --upgrade pip
+#         pip install -r requirements.txt
+#         pip install .
+#     - name: Build docs
+#       run: |
+#         cd docs
+#         make html
+#         # Tell GitHub not to use jekyll to compile the docs
+#         touch build/html/.nojekyll
+#         cd ../
+#     - name: Commit documentation changes
+#       run: |
+#         git clone https://github.com/petercorke/spatialmath-python.git --branch gh-pages --single-branch gh-pages
+#         cp -r docs/build/html/* gh-pages/
+#         cd gh-pages
+#         git config --local user.email "action@github.com"
+#         git config --local user.name "GitHub Action"
+#         git add .
+#         git commit -m "Update documentation" -a || true
+#         # The above command will fail if no changes were present, so we ignore
+#         # that.
+#     - name: Push changes
+#       uses: ad-m/github-push-action@master
+#       with:
+#         branch: gh-pages
+#         directory: gh-pages
+#         github_token: ${{ secrets.GITHUB_TOKEN }}
